name: Deploy Chatbot

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  actions: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker Image
      run: docker build -t vudang0607/llm-serving:latest .

    - name: Push to Registry
      run: docker push vudang0607/llm-serving:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Authenticate with GitHub Token
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
      run: echo "Authenticated successfully"
    - name: Trigger ArgoCD Sync
      run: |
        kubectl apply -f k8s/argocd-app.yaml
        argocd app sync chatbot